tv_cleanup:
  cron: "*/1 * * * *"
  class: "TvCleanupJob"
  queue: default

ghost_solver:
  cron: "*/3 * * * *"
  class: "GhostSolverJob"
  queue: default

trainer_puzzle_generator:
  cron: "0 */1 * * *"
  class: "TrainerPuzzleGeneratorJob"
  queue: default
